#!/bin/bash

# Configure a raw Manjaro installation with nvidia drivers configured.


echo ""
echo "-------------------------------------------------------------------------"
echo "-------------------------------------------------------------------------"
echo "          Installing All Dependencies for Open Suse Leap                 "
echo "                       Please Wait ...                                   "
echo "-------------------------------------------------------------------------"


#==============================================================================
# Commands that will be used during installation.

command='sudo pacman -S '

echo ""
echo "-------------------------------------------------------------------------"
echo " Update the system "

sudo pacman -Syu

echo ""
echo "-------------------------------------------------------------------------"
echo "-------------------------------------------------------------------------"
echo " Installing General stuff..." 

#==============================================================================
# General installation.

$command                  \
vim                       \
gnuplot                   \
tmux                      \
powerline                 \
cgns                      \
paraview                  \
git                       \
texlive-bibtexextra       \
texlive-bin               \
texlive-core              \
texlive-fontsextra        \
texlive-langextra         \
texlive-langgreek         \
texlive-pictures          \
powerline-vim             \
bash-completion

$command                  \
xorg-fonts-75dpi          \   
xorg-fonts-100dpi         \
autoconf                  \
automake                  \
bison                     \
flex                      \
m4                        \
make                      \
patch                     \
gcc-fortran               \
arpack                    \
tcsh                      \
cpio                      \
python                    \
freetype                  \
vim-latexsuite            \
htop                      \
librtmp0                  \
lib32-librtmp0            \
cpio                      \
libzapojit                \
libzip                    \
libzmf                    \
libzdb                    \
libzen                    \
gdb                       \
valgrind                  \
k3b

# Listed by pacman
# pacman -Qe | awk '{print $1}' > package_list.txt

$command                                        \
adwaita-icon-theme                              \
alsa-firmware                                   \
alsa-utils                                      \
arpack                                          \
autoconf                                        \
automake                                        \
avahi                                           \
b43-fwcutter                                    \
baobab                                          \
bash                                            \
bash-completion                                 \
bijiben                                         \
bison                                           \
btrfs-progs                                     \
bzip2                                           \
cgns                                            \
cmake                                           \
coreutils                                       \
cpio                                            \
cppcheck                                        \
cppcodec                                        \
cppunit                                         \
cpupower                                        \
crda                                            \
cronie                                          \
cryptsetup                                      \
cython                                          \
cython2                                         \
dconf-editor                                    \
device-mapper                                   \
devtools                                        \
dhclient                                        \
dhcpcd                                          \
diffutils                                       \
dmidecode                                       \
dmraid                                          \
dnsmasq                                         \
dosfstools                                      \
doxygen                                         \
doxygen-docs                                    \
e2fsprogs                                       \
ecryptfs-utils                                  \
efibootmgr                                      \
eigen                                           \
empathy                                         \
evince                                          \
evolution                                       \
exfat-utils                                     \
f2fs-tools                                      \
ffmpegthumbnailer                               \
file                                            \
file-roller                                     \
filesystem                                      \
findutils                                       \
firefox                                         \
flatpak                                         \
flex                                            \
fltk                                            \
fltk-docs                                       \
fltk-games                                      \
fprintd                                         \
gawk                                            \
gcc-fortran                                     \
gcc-libs                                        \
gdb                                             \
gdm                                             \
gedit                                           \
gettext                                         \
glew1.10                                        \
glibc                                           \
glm                                             \
gnome-backgrounds                               \
gnome-calculator                                \
gnome-calendar                                  \
gnome-characters                                \
gnome-clocks                                    \
gnome-contacts                                  \
gnome-control-center                            \
gnome-desktop                                   \
gnome-disk-utility                              \
gnome-font-viewer                               \
gnome-getting-started-docs                      \
gnome-keyring                                   \
gnome-maps                                      \
gnome-online-accounts                           \
gnome-screenshot                                \
gnome-session                                   \
gnome-settings-daemon                           \
gnome-shell                                     \
gnome-shell-extension-gsconnect                 \
gnome-shell-extension-manjaro-update            \
gnome-shell-extensions                          \
gnome-system-log                                \
gnome-system-monitor                            \
gnome-terminal                                  \
gnome-themes-extra                              \
gnome-todo                                      \
gnome-tweaks                                    \
gnome-user-docs                                 \
gnome-user-share                                \
gnome-wallpapers                                \
gnome-weather                                   \
gnuplot                                         \
gparted                                         \
grep                                            \
grilo-plugins                                   \
grub                                            \
grub-theme-manjaro                              \
gst-libav                                       \
gst-plugins-bad                                 \
gst-plugins-base                                \
gst-plugins-good                                \
gst-plugins-ugly                                \
gtest                                           \
gthumb                                          \
gtk-engine-murrine                              \
gtk3                                            \
gtksourceview-pkgbuild                          \
gufw                                            \
gvfs                                            \
gvfs-afc                                        \
gvfs-google                                     \
gvfs-mtp                                        \
gvfs-smb                                        \
gzip                                            \
haveged                                         \
hexchat                                         \
htop                                            \
illyria-wallpaper                               \
imagewriter                                     \
inetutils                                       \
intel-ucode                                     \
inxi                                            \
iproute2                                        \
iptables                                        \
iputils                                         \
ipw2100-fw                                      \
ipw2200-fw                                      \
jfsutils                                        \
jre8-openjdk                                    \
jre8-openjdk-headless                           \
k3b                                             \
kernel-alive                                    \
less                                            \
lib32-glew1.10                                  \
lib32-libva-vdpau-driver                        \
lib32-mesa-demos                                \
lib32-mesa-vdpau                                \
lib32-nvidia-utils                              \
lib32-primus                                    \
lib32-vulkan-intel                              \
lib32-vulkan-radeon                             \
libdvdcss                                       \
librecad                                        \
libreoffice-fresh                               \
libva-mesa-driver                               \
libva-vdpau-driver                              \
libxml++                                        \
libxml++2.6                                     \
libzdb                                          \
libzen                                          \
libzip                                          \
licenses                                        \
linux-firmware                                  \
linux419                                        \
linux419-bbswitch                               \
linux419-nvidia                                 \
linux419-r8168                                  \
logrotate                                       \
lollypop                                        \
lrzip                                           \
lsb-release                                     \
lvm2                                            \
make                                            \
man-db                                          \
man-pages                                       \
manjaro-alsa                                    \
manjaro-application-utility                     \
manjaro-artwork                                 \
manjaro-aur-support                             \
manjaro-browser-settings                        \
manjaro-documentation-en                        \
manjaro-firmware                                \
manjaro-gdm-check                               \
manjaro-gdm-theme                               \
manjaro-gnome-assets                            \
manjaro-gnome-vanilla                           \
manjaro-hello                                   \
manjaro-hotfixes                                \
manjaro-printer                                 \
manjaro-pulse                                   \
manjaro-release                                 \
manjaro-settings-manager-notifier               \
manjaro-system                                  \
manjaro-wallpapers-18.0                         \
mc                                              \
mcpp                                            \
mdadm                                           \
memtest86+                                      \
mesa-demos                                      \
mesa-vdpau                                      \
metis                                           \
mhwd                                            \
mhwd-db                                         \
mhwd-tui                                        \
mkinitcpio-openswap                             \
mobile-broadband-provider-info                  \
modemmanager                                    \
mousetweaks                                     \
ms-office-online                                \
mutter                                          \
nano                                            \
nautilus                                        \
nautilus-admin                                  \
nautilus-empty-file                             \
netctl                                          \
networkmanager                                  \
networkmanager-openconnect                      \
networkmanager-openvpn                          \
networkmanager-pptp                             \
networkmanager-vpnc                             \
nfs-utils                                       \
nss-mdns                                        \
ntfs-3g                                         \
ntp                                             \
numlockx                                        \
nvidia-utils                                    \
openresolv                                      \
openssh                                         \
os-prober                                       \
p7zip                                           \
pacman                                          \
pacui                                           \
pamac                                           \
papirus-maia-icon-theme                         \
paraview                                        \
patch                                           \
pciutils                                        \
perl                                            \
polkit-gnome                                    \
powerline                                       \
powerline-vim                                   \
powertop                                        \
procps-ng                                       \
psmisc                                          \
pulseaudio-bluetooth                            \
pulseaudio-ctl                                  \
pulseaudio-zeroconf                             \
python-breathe                                  \
python-pip                                      \
python-scikit-learn                             \
python-scipy                                    \
python-statsmodels                              \
python2-breathe                                 \
python2-matplotlib                              \
python2-mpi4py                                  \
python2-scikit-learn                            \
python2-scipy                                   \
python2-statsmodels                             \
ranger                                          \
reiserfsprogs                                   \
rsync                                           \
s-nail                                          \
seahorse                                        \
sed                                             \
shadow                                          \
simple-scan                                     \
simplespectral                                  \
spectre-meltdown-checker                        \
steam-manjaro                                   \
sudo                                            \
sushi                                           \
swig                                            \
sysfsutils                                      \
systemd-fsck-silent                             \
systemd-sysvcompat                              \
tar                                             \
tcsh                                            \
telepathy-accounts-signon                       \
terminus-font                                   \
texinfo                                         \
texlive-bibtexextra                             \
texlive-fontsextra                              \
texlive-formatsextra                            \
texlive-humanities                              \
texlive-langcyrillic                            \
texlive-langextra                               \
texlive-langgreek                               \
texlive-music                                   \
texlive-pictures                                \
texlive-pstricks                                \
texlive-publishers                              \
texlive-science                                 \
timeshift                                       \
tlp                                             \
tmux                                            \
totem                                           \
tracker                                         \
tracker-miners                                  \
transmission-gtk                                \
ttf-bitstream-vera                              \
ttf-dejavu                                      \
ttf-droid                                       \
ttf-inconsolata                                 \
ttf-indic-otf                                   \
ttf-liberation                                  \
uget                                            \
unace                                           \
unrar                                           \
usb_modeswitch                                  \
usbutils                                        \
util-linux                                      \
valgrind                                        \
vi                                              \
vim                                             \
vino                                            \
vulkan-intel                                    \
vulkan-radeon                                   \
w3m                                             \
wallpapers-2018                                 \
wget                                            \
which                                           \
wine                                            \
wpa_supplicant                                  \
xdg-su                                          \
xdg-user-dirs                                   \
xdg-user-dirs-gtk                               \
xdg-utils                                       \
xf86-input-elographics                          \
xf86-input-evdev                                \
xf86-input-keyboard                             \
xf86-input-libinput                             \
xf86-input-mouse                                \
xf86-input-void                                 \
xf86-input-wacom                                \
xf86-video-amdgpu                               \
xf86-video-ati                                  \
xf86-video-intel                                \
xf86-video-nouveau                              \
xfsprogs                                        \
xorg-fonts-100dpi                               \
xorg-fonts-75dpi                                \
xorg-server                                     \
xorg-twm                                        \
xorg-xinit                                      \
yelp                                            \
zsh
